export const AUTO_LOGIN_LOADING = "AUTO_LOGIN_LOADING"
export const AUTO_LOGIN_SUCCESS = "AUTO_LOGIN_SUCCESS"
export const AUTO_LOGIN_FAIL = "AUTO_LOGIN_FAIL"

export const LOGIN_WITH_OAUTH_LOADING = "LOGIN_WITH_OAUTH_LOADING"
export const LOGIN_WITH_OAUTH_SUCCESS = "LOGIN_WITH_OAUTH_SUCCESS"
export const LOGIN_WITH_OAUTH_FAIL = "LOGIN_WITH_OAUTH_FAIL"

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"

export const GET_PROFILE_LOADING = "GET_PROFILE_LOADING"
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS"
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL"

export const EDIT_USER_LOADING = "EDIT_USER_LOADING"
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS"
export const EDIT_USER_FAIL = "EDIT_USER_FAIL"

export const DELETE_USER_LOADING = "DELETE_USER_LOADING"
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"
export const DELETE_USER_FAIL = "DELETE_USER_FAIL"

export const UPDATE_USER_LOADING = "UPDATE_USER_LOADING"
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"
